// Mock data untuk auctioned items (approved)
export const mockAuctionedItems = [
  {
    id: "mock-auction-1",
    title: "Luxury Villa in Bali",
    description: "A stunning 5-bedroom villa with ocean view, perfect for vacation rental investment",
    imageUrl: "/placeholder.svg",
    category: "Real Estate",
    currentPrice: "2.5",
    currency: "ETH" as const,
    status: "live" as const,
    endTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    sellerId: "current-user",
    adminStatus: "approved" as const,
    bidCount: 8,
    highestBidder: "0x742d35Cc6645C4532532532",
  },
  {
    id: "mock-auction-2",
    title: "Commercial Building Jakarta",
    description: "Prime location commercial building in Jakarta CBD, fully occupied with stable tenants",
    imageUrl: "/placeholder.svg",
    category: "Real Estate",
    currentPrice: "15.8",
    currency: "ETH" as const,
    status: "closed" as const,
    endTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    sellerId: "current-user",
    adminStatus: "approved" as const,
    bidCount: 12,
    finalPrice: "18.2",
    winner: "0x8876543210987654321",
  },
  {
    id: "mock-auction-3",
    title: "Apartment Complex Surabaya",
    description: "Modern 24-unit apartment complex with full amenities and parking",
    imageUrl: "/placeholder.svg",
    category: "Real Estate",
    currentPrice: "8.3",
    currency: "ETH" as const,
    status: "live" as const,
    endTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
    sellerId: "current-user",
    adminStatus: "approved" as const,
    bidCount: 5,
    highestBidder: "0x123456789abcdef123456",
  },
  {
    id: "mock-auction-4",
    title: "Office Space Bandung",
    description: "Strategic office space in Bandung business district, ready to occupy",
    imageUrl: "/placeholder.svg",
    category: "Real Estate",
    currentPrice: "12000",
    currency: "IDRX" as const,
    status: "live" as const,
    endTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    sellerId: "current-user",
    adminStatus: "approved" as const,
    bidCount: 3,
    highestBidder: "0xabcdef123456789abcdef",
  },
];
